### ISSUE TITLE
UnlitWFのOverlay系のシェーダーエラーが発生する

### ISSUE THREAD

**Issue by GaoLiar** [OmochiNobiru/DPSShaderGenerator2#2]
シェーダーにて以下のエラーが出る

### ファイル
Unlit_WF_UnToon_Opaque_Penetrator_Overlay.shader
Unlit_WF_UnToon_Transparent_Orifice_Overlay.shader

### エラー内容
invalid subscript 'instanceID' 'UnitySetupInstanceID': no matching 1 parameter function
Compiling Vertex program with UNITY_PASS_SHADOWCASTER SHADOWS_DEPTH STEREO_INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

### 環境
Unityバージョン: 2019.4.31f
XR Settings Stereo Rendering Mode：Single Pass

### 修正案
`                        writer.WriteLine("UNITY_VERTEX_INPUT_INSTANCE_ID");`
上記コードをEditor/DPSShaderGeneratorFW.csの463行目と500行目に追加
（プルリク投げられなくてすみません）

**Comment by OmochiNobiru** [comment]
最新版（10.0）で修正しました。遅くなってしまい申し訳ないです。
